#!/bin/bash
#
# This script is made entirely by me, dmitry pervushin
# May be, it shows lack of programming skills. May be, it shows something else
# In any way, feel free to use it of you need one.
#
# Author declines ANY responsability for ANY damages, direct or indirect, that
# caused, will be caused or might be caused by this script. You use it on your
# own risk
#

PRJ_VERSION="20260820"

[ -r "$HOME/hosts/load-private" ] && . "$HOME/hosts/load-private"

function force_sudo() {
	echo "Might need your password"
	sudo -v
	echo "OK"
}

function _require_safe_directory() {
	local path="$1"
	local description="${2:-directory}"

	if [ -z "$path" ] || [ "$path" = "/" ] || [ ! -d "$path" ]; then
		echo "Refusing destructive operation: unsafe $description: '$path'" >&2
		return 1
	fi
}

function mko() {
	mkdir -p $TARGET_O
	[ $PRJ_SILENT -eq 0 ] && echo "Directory $TARGET_O created"
}

function mkroot() {
	if [ -e $TARGET_ROOT ]; then
		return
	fi
	mkdir -p $TARGET_ROOT
	[ $PRJ_SILENT -eq 0 ] && echo "Directory $TARGET_ROOT created"
}

function M() {
	PRJ_SILENT=1 mko && mkroot
	set -x
	make 					\
		O=$TARGET_O 			\
		ARCH=$TARGET_CPUARCH 		\
		CROSS_COMPILE=$TARGET_CROSS 	\
		INSTALL_MOD_PATH=$TARGET_ROOT 	\
		"$@" 				\
		$JOPT
	set +x
}

function MM() {
	PRJ_SILENT=1 M "$TARGET_TARGET" "$@"
}

function m() {
	PRJ_SILENT=1 M modules && M modules_install
}

function Mm() {
	PRJ_SILENT=1 M && m
}

function Mz() {
	PRJ_SILENT=1 M zImage "$@"
}

function Mu() {
	PRJ_SILENT=1 M uImage "$@"
}

function do_copy_using1() {
	local copy_command="$1"
	local source="$TARGET_O/$2"
	local destination="$TARGET_TFTP/$3"
	local FS
	FS=$(_filesize "$source")
	[ "$PRJ_SILENT" -eq 0 ] && echo "# ($source) =>"
	[ "$PRJ_SILENT" -eq 0 ] && echo "# => ($TARGET_TFTP) $3 size $FS"
	"$copy_command" "$source" "$destination"
}

function do_copy_using() {
	local CP_CMD
	if [ $# -ge 1 ]; then
		CP_CMD="$1"
		shift
	fi

	if [ $# -ge 2 ]; then
		while [ $# -ge 2 ]; do
			do_copy_using1 "$CP_CMD" "$1" "$2"
			shift
			shift
		done
	else
		do_copy_using1 "$CP_CMD" "$TARGET_PATH/$TARGET_TARGET" "$TARGET_TARGET_BIN"
	fi
}

function C() {
	do_copy_using "$TARGET_CUSTOM_CP" "$@"
}

function Cc() {
	do_copy_using cp "$@"
}

function U() {
	make CROSS_COMPILE="$TARGET_CROSS" O="$TARGET_U" ARCH="$TARGET_CPUARCH" "$@"
}

function u() {
	fs=$(_filesize $TARGET_U/u-boot.bin)
	[ $PRJ_SILENT -eq 0 ] && echo "# => ($TARGET_TFTP) $TARGET_UBOOT_BIN size ${FS}"
	scp $TARGET_U/u-boot.bin $TARGET_TFTP/$TARGET_UBOOT_BIN
}

function MC() {
	PRJ_SILENT=1 MM "$@" && PRJ_SILENT=1 C
}

function MCL() {
	PRJ_SILENT=1 MM && C && L
}

function CL() {
	PRJ_SILENT=1 C && L
}

function Uu() {
	PRJ_SILENT=1 U && u
}

function cf() {
	cp -v $1 ${TARGET_O}/.config
	PRJ_SILENT=1 M oldconfig
}

function L() {
	~/bin/lds "$TARGET_TARGET_BIN" "$@"
}

function v() {
	args=$(printf '%s' "$*" | sed 's/:/ +/' | sed 's/://g')
#	echo "VI $args"
	vim --cmd "set tags=${TARGET_O}/tags,${TARGET_U}/ctags" $args
}

function build-v2() {
	export TEGRA_TOP=$PWD
	echo $TEGRA_TOP
	export EMBEDDED_TARGET_PLATFORM=p852m-linux
	export TEGRA_ROOT=${TEGRA_TOP}/core
	export KERN_DIR=${TEGRA_TOP}/kernel
	export TARGET_CPU=armv6
	export TARGET_OS=linux
	export TARGET_OS_SUBTYPE=gnu_linux
	export BUILD_FLAVOR=release
	export TARGET_NFS_ROOT=${TEGRA_ROOT}/targetfs
	export NV_EMBEDDED_BUILD=1
	export TARGET_BOARD=p852
	export TARGET_BOOT_MEDIUM=nand
	export TARGET_FLOAT_ABI_HARD=1
	export WIN_INTERFACE=x11
	export TARGET_PLATFORM=$EMBEDDED_TARGET_PLATFORM
	export ARMLMD_LICENSE_FILE=1924@sc-lic-18:1924@sac-lic-19

	make -C core/mobile_linux/make "$@"
}

function flash-v2() {
	pushd utils/scripts/burnflash
	./burnflash.sh -S 23 -Z lzf -n eth0 -b nand
	popd
}

function with() {
	python3 /home/dimka/projects/nvidia/lab/with/main.py "$@" | bash
#	python /opt/shoelace/with.py $*
}


function tgv-target() {
	cd /root/tgv || return
	rm -f -- ./*result*.csv
	/home/nvidia/tegra_golden_value -c t194 -f internal*.csv
}

function tgv-host() {
	local conf="${1:-LEBP}"
	local dtb="$HOME/projects/nvidia/v5/NTG7/R/out/embedded-linux-t186ref-release/nvidia/kernel/arch/arm64/boot/dts/tegra194-chiem-c02-vm1.dtb"
	local tgv="$HOME/P/nvidia/v5/NTG7/R/tools/golden-regs-rel/stable"
	local ht="$tgv/gr_host_tools_python3"
	local status
	local -a conf_args

	[ "$#" -gt 0 ] && shift
	if [ "$conf" = "LEBP" ]; then
		conf_args=(-dtb "$dtb")
	else
		conf_args=(-ig)
	fi

	setup-vars-tegra || return
	set -x
	time python3 "$ht/tgv_tool/tgv.py" \
		-c t194 \
		-m CHIEM2 \
		-s 0004 \
		-r D \
		-pkg VCM \
		-pf PDK \
		-cr A02 \
		-type internal \
		-sw_conf "$conf" \
		"${conf_args[@]}" \
		-bb MICRON_16 \
		-use_snapshot \
		-ppc "$ht/common/PPC_files/T194/CHIEM2_Platform_POR_Configuration.csv" \
		"$@"
	status=$?
	set +x
	return "$status"
}

function setup-vars-misra() {
	BUILD_AUTOMATION="/home/dimka/projects/nvidia/coverity/build-automation"
	COVERITY_HOME="${P4ROOT}/sw/mobile/tools/coverity/coverity_2023.6.0"

	NV_COMPONENT="$1"
	BUILD_BRAIN_COMPONENT=$(echo -n "${nvc}" | tr ' ' '_')
	TOP=${VR}
	HTML=${VR}/html-output
}

function build-misra() {
	local nvc=$1

	if [ -z "${nvc}" ]; then
		echo "Usage: build-misra 'NV_COMPONENT'"
		return
	fi

	setup-vars-tegra
	setup-vars-misra "${nvc}"
	_require_safe_directory "$VR" "VR" || return
        export NV_COMPONENT BUILD_BRAIN_COMPONENT TOP

	rm --recursive --force -- "$VR/artifacts"
	pushd ${BUILD_AUTOMATION}/tools/build-scripts/gobuild 2>&1 >/dev/null
        env | grep NV
        ./gobuild.py
	popd 2>&1 >/dev/null
}

function misra-scan() {

        setup-vars-tegra
	_require_safe_directory "$VR" "VR" || return
	COVERITY_HOME="${P4ROOT}/sw/mobile/tools/coverity/coverity_2023.6.0"
	HTML=${VR}/html-output

	rm --recursive --force -- "$HTML"
	${COVERITY_HOME}/bin/cov-analyze \
                --dir=${VR}/emit-coverity \
                --misra-config=${P4ROOT}/sw/tools/Coverity/2023.12.0/Linux64/config/MISRA/MISRA_c2012_nv.config \
                --strip-path=/home/dimka/projects/nvidia/v6/r37/R \
                --disable-default --ignore-deviated-findings \
                -co MISRA_CAST:non_negative_literals_may_be_unsigned:true \
                --jobs 8 --max-mem 500 \
                --tu 36727,36728,36729,36730,36731,36732,36733,36734,36735,36736,36737,36738
	${COVERITY_HOME}/bin/cov-format-errors --dir=${VR}/emit-coverity --html-output=${HTML} \
		--include-files='./qnx/src/resmgrs/nvdvms/*'
}

function tgv-host-ddpx() {
	local conf="${1:-LEBP}"
	local dtb="$HOME/projects/nvidia/v5/NTG/R/out/embedded-linux-t186ref-release/nvidia/kernel/arch/arm64/boot/dts/tegra194-e3550-0001-b03-A.dtb"
	local tgv
	local -a conf_args

	[ "$#" -gt 0 ] && shift
	if [ "$conf" = "LEBP" ]; then
		conf="E3550-XA_LEBP"
		conf_args=(-dtb "$dtb")
	fi

	setup-vars-tegra || return
	tgv="$VR/tools/golden-regs-rel/1.7/gr_host_tools/tgv_tool"
	time python "$tgv/tgv.py" \
		-c t194 \
		-m E3550-XA \
		-s 0001 \
		-r B03 \
		-pkg MID \
		-pf PDK \
		-cr A02 \
		-type internal \
		-sw_conf "$conf" \
		"${conf_args[@]}" \
		-use_snapshot \
		-ppc "$tgv/../common/PPC_files/T194/E3550_Platform_POR_Configuration.xlsx" \
		"$@"
}


function export-tegratop() {
	local TEGRA_TOP=''
	pushd $1/.. 2>&1 >/dev/null
	TEGRA_TOP=$(/bin/pwd)
	popd 2>&1 >/dev/null
	echo -n $TEGRA_TOP
}

function setup-vars-tegra() {
	TEGRA_REPO=$(nvpath -n --action=root)
	TEGRA_TOP=$(export-tegratop $TEGRA_REPO)
	VF=$TEGRA_TOP/foundation
	VL=$TEGRA_TOP/linux
	VQ=$TEGRA_TOP/qnx
        VR=$TEGRA_REPO
        say "### VR = ${VR}\n"
	export TEGRA_TOP VF VL VQ VR
}

function netapp39() {
   tr '\\' '/' | sed -e 's~/netapp39~netapp39~' | sed -e 's~//~~'
}

function mount-smbfs() {
   force_sudo
   sudo mkdir -p /mnt/smb
   sudo mount -t cifs -o user="${NVIDIA_SMB_USER:?NVIDIA_SMB_USER is not configured}",password="${NVIDIA_SMB_PASSWORD:?NVIDIA_SMB_PASSWORD is not configured}",domain=nvidia.com //$(netapp39 $1) /mnt/smb
}

function hwy-do() {
   local COMMAND=$1
   lftp -e "set ssl:verify-certificate no; ${COMMAND}; quit" \
		ftp://${NVIDIA_HWY_USER:?NVIDIA_HWY_USER is not configured}:${NVIDIA_HWY_PASSWORD:?NVIDIA_HWY_PASSWORD is not configured}@hqnvhwy02
}

function hwy-get() {
   local DIR_PATH="$1"
   local WILDCARD="$2"
   hwy-do "ls ${DIR_PATH}/${WILDCARD}; mirror $DIR_PATH -r -I $WILDCARD --use-pget-n=10"
}

function hwy() {
   local DIR_PATH=$1
   local WILDCARD="*.7z*"
   hwy-get "${DIR_PATH}" "${WILDCARD}"
}


function hwy-ls() {
   local DIR_PATH=$1
   hwy-do "ls ${DIR_PATH}"
}

function download-build() {
   set -x
   pushd $(pwd) 2>&1 > /dev/null
   W=$(mktemp --directory)
   mkdir -p $W/F && cd $W/F && hwy $(echo "$1" | netapp39)
   mkdir -p $W/L && cd $W/L && hwy $(echo "$2" | netapp39)
   cd $W && for zip in F/*/*001 L/*/*001; do 7z x $zip; done
   popd 2>&1 >/dev/null
   set +x
   echo "Downloaded to ${W}"
}

function install-runs() {
   export _NV_INSTALL_LICENSE_BYPASS_="Destination Tegra Dominance"
   export D=$DISPLAY
   unset DISPLAY

   for run in {$1,$2}/*foundation*-toolchain.run \
            {$1,$2}/*foundation*-release-sdk.run \
            {$1,$2}/*foundation*-release-pdk.run \
            {$1,$2}/*foundation*-oss-src.run \
            {$1,$2}/*linux*-initramfs.run \
            {$1,$2}/*linux*-rootfs.run \
            {$1,$2}/*linux*-oss-minimal-sdk.run \
            {$1,$2}/*linux*-oss-minimal-pdk.run \
            {$1,$2}/*linux*-oss-src.run \
            {$1,$2}/*linux*-nv-minimal-sdk.run \
            {$1,$2}/*linux*-nv-minimal-pdk.run; do
      if [ ! -f "${run}" ]; then
          echo "${run} does not exist, skipping"
          continue
      fi
      yes '' | bash ${run}
   done
   export DISPLAY=$D
}

function configure-tegra() {
	echo -ne ''
	echo -ne "source ${VR}/tmake/scripts/envsetup.sh 2>&1 >/dev/null; "
	echo -ne "choose $1;"
	echo -ne "$2;"
	echo -ne ''
}


function nv-do() {
	local CFG_ARGS=$1
	shift
	local CFG_EXTRA=$1
	shift
	local CMD_ARGS="$*"

        setup-vars-tegra
#	eval $(configure-tegra "${CFG_ARGS}" "${CFG_EXTRA}")
        eval "source ${VR}/tmake/scripts/envsetup.sh 2>&1 >/dev/null; choose ${CFG_ARGS}; ${CFG_EXTRA}"
	say "Running $CMD_ARGS\n"
	eval $CMD_ARGS
}

function nv() {
	#
	# currently accepted options: s, r,d, q,f,l, 1 and -
	#
	local SAFETY=none
	local RELEASE=release
	local TYPE=idk
	local CHIP="generic"
	local KVARIANT="/bin/true"
	local arg unknown length char i

	if [ "$#" -eq 0 ]; then
		echo "Usage: nv OPTIONS -- COMMAND [ARG ...]" >&2
		return 2
	fi

	while [ "$#" -gt 0 ]; do
		arg="$1"
		unknown=0
		length=${#arg}
		for ((i = 0; i < length; i++)); do
			char="${arg:i:1}"
			case "${char}" in
			s) SAFETY="safety";;
			r) RELEASE="release";;
			d) RELEASE="debug";;
			q) TYPE="qnx";;
			f) TYPE="foundation";;
			l) TYPE="linux";;
			1) CHIP="t186ref";;
			8) CHIP="t186ref";;
			-) unknown=1;shift;break;;
			*) unknown=1;break;;
			esac
		done
		if [ ${unknown} -ne 0 ]; then
			break
		fi
		shift
	done
	construction="embedded-${TYPE} ${CHIP} ${SAFETY} ${RELEASE} external"
	if [ ${TYPE} == "linux" ]; then construction="${construction} aarch64"; fi
	# say "Construction = '${construction}'\n"
	nv-do "${construction}" "${KVARIANT}" "$@"
}

function setup() {
	[ -f ~/.nvidia-colossus-host ] && get-colossus

#	for alias in M MM Mz Mu C U u Uu MC cfi L MCL CL v m Mm mko mkroot nv NC nvf nvq nvl; do
#		alias $alias=". $SCRIPT $alias"
#	done

#        setup-vars-tegra
	say "### setup, version ${PRJ_VERSION}\n"
#	cd $HOME
}

function fix_arch() {
	if [ "x$TARGET_ARCH" != "x" ]; then
		echo "TARGET_ARCH is deprecated, forcing to set TARGET_CPUARCH = '$TARGET_ARCH'"
		export TARGET_CPUARCH=$TARGET_ARCH
		unset -v TARGET_ARCH
	fi
}

function ps1() {
	local param_color=$1
	local prompt_symbol="%"

	if [ "$EUID" -eq 0 ]; then
		prompt_symbol="#"
	fi

	echo -n "\[${COLOR_Reset}\]"
	if [ "$(is-git-controlled)" != "" ]; then
		echo -n "\[${COLOR_Green}\]git \[${COLOR_Reset}\]"
	fi
	#echo -n '\[$(is-git-shallowed)\] * \[${COLOR_Reset}\]'
	echo -n "\[${param_color}\]"
	echo -n '(\h:'
	split_pwd=($(pwd | sed "s:^${HOME}:/~:" | tr ' ' '\a' | tr '/' ' '))
	for pwd_item in ${split_pwd[*]}; do
		color="${param_color}"
                #
                # Oooh, welcome to regex horror
                #
                # it passes if the string (bnetween ^...$) is:
                #     V + character
                #     R + digits
                #     REL + digits
                #     REL- + digits
                #     NTG6 or NTG7
                #     MAIN, DEV-MAIN or MBITION
                #
		if printf '%s' "$pwd_item" | tr '[:lower:]' '[:upper:]' | command grep -qE '^(V.?|R[0-9]+|REL[0-9]+|REL-.*|NTG[6-7]|MAIN|DEV-MAIN|MBITION)$'; then
			color="${COLOR_Cyan}"
		fi
		echo -n "\[${color}\]"
		if [ ${pwd_item} != "~" ]; then
			echo -n "/"
		fi
		echo -n "${pwd_item}" | tr '\a' ' '
	done
	echo -n ")\[${COLOR_Reset}\] "
	echo -n "${prompt_symbol} \[${COLOR_Reset}\]"
}

function ps1_helper() {
	export PS1=$(ps1 $1)
}

function say() {
	printf '%s%b%s' "${COLOR_Magenta:-}" "$*" "${COLOR_Reset:-}"
}

function late_init() {
	echo -n ""
}

function _filesize() {
	ls -nl $1 | awk '{print $5}'
}

function _do() {
	local VAR=$1
	shift
	"$@" "$VAR"
}

function _do_all() {
	for v in $1; do
		_do $v $2
	done
}

function shell-scripts-check() {
	local required_commands="sh bash git cp chmod mkdir touch ln dirname basename pwd hostname grep sed tr date cmp readlink"
	local optional_commands="tput make ssh scp rsync python3 vim"
	local cmd path
	local missing=0

	echo "# Required commands"
	for cmd in $required_commands; do
		if path=$(command -v "$cmd" 2>/dev/null); then
			printf 'ok      %-10s %s\n' "$cmd" "$path"
		else
			printf 'missing %-10s\n' "$cmd"
			missing=1
		fi
	done

	echo "# Optional commands used by common helpers"
	for cmd in $optional_commands; do
		if path=$(command -v "$cmd" 2>/dev/null); then
			printf 'ok      %-10s %s\n' "$cmd" "$path"
		else
			printf 'optional %-9s not found\n' "$cmd"
		fi
	done

	return "$missing"
}

function _shell_scripts_repo() {
	if [ -n "${SHELL_SCRIPTS_REPO:-}" ]; then
		printf '%s\n' "$SHELL_SCRIPTS_REPO"
	elif [ -d "$HOME/P" ]; then
		printf '%s\n' "$HOME/P/home-shell-scripts"
	else
		printf '%s\n' "$HOME/home-shell-scripts"
	fi
}

function _shell_scripts_managed_installed_files() {
	local repo="$1"
	local relative

	printf '%s\t%s\n' "$repo/bash_profile" "$HOME/.bash_profile"
	printf '%s\t%s\n' "$repo/prj" "$HOME/bin/prj"
	printf '%s\t%s\n' "$repo/project-vars" "$HOME/defaults/project-vars"
	while IFS= read -r relative; do
		printf '%s\t%s\n' "$repo/$relative" "$HOME/$relative"
	done < <(git -C "$repo" ls-files -- bin)
}

function _shell_scripts_canonical_directory() {
	(
		CDPATH=
		cd "$1" 2>/dev/null && pwd -P
	)
}

function _shell_scripts_installed_hosts_target() {
	local target
	[ -L "$HOME/hosts" ] || return 1
	target=$(readlink "$HOME/hosts") || return 1
	case "$target" in
		/*) ;;
		*) target="$(dirname "$HOME/hosts")/$target" ;;
	esac
	_shell_scripts_canonical_directory "$target"
}

function _shell_scripts_file_matches_history() {
	local repo="$1"
	local relative="$2"
	local installed_file="$3"
	local installed_blob commit blob
	installed_blob=$(git -C "$repo" hash-object "$installed_file") || return 1

	while IFS= read -r commit; do
		blob=$(git -C "$repo" rev-parse "$commit:$relative" 2>/dev/null) || continue
		[ "$blob" = "$installed_blob" ] && return 0
	done < <(git -C "$repo" log --format='%H' --all -- "$relative")
	return 1
}

function _shell_scripts_installed_has_edits() {
	local repo="$1"
	local repo_file installed_file relative

	while IFS=$'\t' read -r repo_file installed_file; do
		relative=${repo_file#"$repo/"}
		[ -e "$installed_file" ] || return 0
		if ! cmp -s "$repo_file" "$installed_file" && ! _shell_scripts_file_matches_history "$repo" "$relative" "$installed_file"; then
			return 0
		fi
	done < <(_shell_scripts_managed_installed_files "$repo")
	return 1
}

function _shell_scripts_installed_is_clean() {
	local repo="$1"
	local repo_file installed_file
	local installed_hosts repo_hosts

	while IFS=$'\t' read -r repo_file installed_file; do
		[ -e "$installed_file" ] || return 1
		cmp -s "$repo_file" "$installed_file" || return 1
	done < <(_shell_scripts_managed_installed_files "$repo")

	installed_hosts=$(_shell_scripts_installed_hosts_target) || return 1
	repo_hosts=$(_shell_scripts_canonical_directory "$repo/hosts") || return 1
	[ "$installed_hosts" = "$repo_hosts" ] || return 1
	return 0
}

function _shell_scripts_diff_installed() {
	local repo="$1"
	local repo_file installed_file relative
	local installed_hosts="" repo_hosts

	echo "# Installed file differences"
	while IFS=$'\t' read -r repo_file installed_file; do
		relative=${repo_file#"$repo/"}
		if [ ! -e "$installed_file" ]; then
			echo "missing installed file: $installed_file ($relative)"
		elif ! cmp -s "$repo_file" "$installed_file"; then
			echo "## $relative differs from $installed_file"
			git --no-pager diff --no-index -- "$repo_file" "$installed_file" || [ $? -eq 1 ] || return
		fi
	done < <(_shell_scripts_managed_installed_files "$repo")

	repo_hosts=$(_shell_scripts_canonical_directory "$repo/hosts") || return
	installed_hosts=$(_shell_scripts_installed_hosts_target) || true
	if [ -z "$installed_hosts" ]; then
		echo "missing installed symlink: $HOME/hosts -> $repo/hosts"
	elif [ "$installed_hosts" != "$repo_hosts" ]; then
		echo "wrong installed symlink: $HOME/hosts -> $(readlink "$HOME/hosts")"
		echo "expected: $HOME/hosts -> $repo_hosts"
	fi
}

function shell-scripts-capture-installed() {
	local repo repo_file installed_file relative
	local missing=0
	repo=$(_shell_scripts_repo)
	git -C "$repo" rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
		echo "Not a Git work tree: $repo" >&2
		return 1
	}

	while IFS=$'\t' read -r repo_file installed_file; do
		relative=${repo_file#"$repo/"}
		if [ ! -e "$installed_file" ]; then
			echo "Cannot capture missing installed file: $installed_file" >&2
			missing=1
		elif ! cmp -s "$repo_file" "$installed_file"; then
			cp -p "$installed_file" "$repo_file" || return
			echo "Captured $installed_file -> $relative"
		fi
	done < <(_shell_scripts_managed_installed_files "$repo")

	return "$missing"
}

function shell-scripts-update() {
	local repo
	repo=$(_shell_scripts_repo)
	git -C "$repo" rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
		echo "Not a Git work tree: $repo" >&2
		return 1
	}
	git -C "$repo" checkout master || return
	git -C "$repo" pull --rebase --autostash "$@" origin master || return
	"$repo/shell-scripts-install" || return

	# Use the freshly installed definitions in this shell as well as in new ones.
	source "$HOME/bin/prj" setup
}

function shell-scripts-diff() {
	local repo
	local base="master"
	repo=$(_shell_scripts_repo)
	git -C "$repo" rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
		echo "Not a Git work tree: $repo" >&2
		return 1
	}

	git -C "$repo" rev-parse --verify master >/dev/null 2>&1 || {
		echo "Branch not found: master" >&2
		return 1
	}

	if git -C "$repo" rev-parse --verify origin/master >/dev/null 2>&1; then
		base="origin/master"
	fi

	echo "# Repository diff against $base"
	git -C "$repo" status --short --branch
	git -C "$repo" diff --check "$base" || return
	git -C "$repo" diff "$base"
	_shell_scripts_diff_installed "$repo"
}

function shell-scripts-check-daily() {
	local repo cache_dir stamp today last_check=""
	local head_commit remote_commit
	local remote_newer=0 local_newer=0 installed_changed=0 installed_stale=0
	repo=$(_shell_scripts_repo)
	git -C "$repo" rev-parse --is-inside-work-tree >/dev/null 2>&1 || return 0

	cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/home-shell-scripts"
	stamp="$cache_dir/daily-check"
	today=$(date '+%Y-%m-%d') || return
	[ -r "$stamp" ] && IFS= read -r last_check < "$stamp"
	if [ "${1:-}" != "--force" ] && [ "$last_check" = "$today" ]; then
		return 0
	fi
	mkdir -p "$cache_dir" || return
	printf '%s\n' "$today" > "$stamp"

	if ! git -C "$repo" fetch --quiet origin master; then
		echo "home-shell-scripts: daily GitHub check failed; will retry tomorrow." >&2
		return 0
	fi

	head_commit=$(git -C "$repo" rev-parse HEAD) || return
	remote_commit=$(git -C "$repo" rev-parse origin/master) || return
	if [ "$head_commit" != "$remote_commit" ]; then
		if git -C "$repo" merge-base --is-ancestor "$head_commit" origin/master; then
			remote_newer=1
		elif git -C "$repo" merge-base --is-ancestor origin/master "$head_commit"; then
			local_newer=1
		else
			remote_newer=1
			local_newer=1
		fi
	fi

	[ -n "$(git -C "$repo" status --porcelain)" ] && local_newer=1
	if ! _shell_scripts_installed_is_clean "$repo"; then
		if _shell_scripts_installed_has_edits "$repo"; then
			local_newer=1
			installed_changed=1
		else
			installed_stale=1
		fi
	fi

	if [ "$remote_newer" -eq 0 ] && [ "$local_newer" -eq 0 ] && [ "$installed_stale" -eq 0 ]; then
		return 0
	fi

	shell-scripts-diff
	if [ "$remote_newer" -eq 0 ] && [ "$local_newer" -eq 0 ] && [ "$installed_stale" -eq 1 ]; then
		echo "home-shell-scripts: installed copies are older than the repository."
		echo "Suggested reinstall: \"$repo/shell-scripts-install\""
	elif [ "$remote_newer" -eq 1 ] && [ "$local_newer" -eq 0 ]; then
		echo "home-shell-scripts: GitHub master is newer."
		echo "Suggested update: shell-scripts-update"
	elif [ "$remote_newer" -eq 0 ] && [ "$local_newer" -eq 1 ]; then
		echo "home-shell-scripts: local repository or installed files have changes."
		[ "$installed_changed" -eq 1 ] && echo "If the installed edits are intentional, capture them: shell-scripts-capture-installed"
		[ "$installed_stale" -eq 1 ] && echo "Reinstall stale copies: \"$repo/shell-scripts-install\""
		echo "Suggested publish: shell-scripts-push"
	else
		echo "home-shell-scripts: GitHub and local files both have changes."
		[ "$installed_changed" -eq 1 ] && echo "If the installed edits are intentional, capture them first: shell-scripts-capture-installed"
		[ "$installed_stale" -eq 1 ] && echo "Installed copies are stale; reinstall after merging."
		echo "Review above, then merge: git -C \"$repo\" merge origin/master"
	fi
}

function shell-scripts-push() {
	local repo
	local message="${*:-Update shell scripts}"
	local current_branch
	repo=$(_shell_scripts_repo)
	git -C "$repo" rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
		echo "Not a Git work tree: $repo" >&2
		return 1
	}
	current_branch=$(git -C "$repo" symbolic-ref --quiet --short HEAD) || {
		echo "Cannot determine the current Git branch" >&2
		return 1
	}
	if [ "$current_branch" != "master" ]; then
		echo "Refusing to commit shell-scripts outside branch master" >&2
		return 1
	fi

	git -C "$repo" add -- . || return
	git -C "$repo" diff --cached --check || return
	if ! git -C "$repo" diff --cached --quiet; then
		git -C "$repo" commit -m "$message" || return
	else
		echo "No shell-scripts changes to commit"
	fi
	git -C "$repo" push origin master
}

function repo-top() {
       repo forall -c 'git checkout -b T HEAD; git branch --delete --force t; git checkout -b t HEAD; git branch --delete --force T'
}

function gerrit-push() {
       say "Pushing changed for review to branch \"$1\"\n"
       git push origin HEAD:refs/for/$1
}

function unshallow() {
       git fetch --unshallow origin
}

function repo-setup-mods() {
	local BRANCH=$1
	local REF=/y/reference/$1
	local TEGRA_R="M"

	mkdir ${TEGRA_R}
	cd ${TEGRA_R}
	repo init \
		--manifest-url=git://git-master.nvidia.com/tegra/manifest.git 	\
		--manifest-branch=${BRANCH} 					\
		--manifest-name=mods-linux.xml					\
		--reference=${REF}
}


function repo-setup-auto() {
	local BRANCH=$1
	local REF=/y/reference/$1
	local TEGRA_R="R"
        local REF_OPTION

	mkdir -p ${TEGRA_R}
	ln -sf ${TEGRA_R} foundation
	ln -sf ${TEGRA_R} linux
	ln -sf ${TEGRA_R} qnx
	cd ${TEGRA_R}
        if [ -d ${REF} ]; then
             REF_OPTION="--reference=${REF}"
        else
             say "Warning - ${REF} does not exist, using without reference"
             REF_OPTION=""
        fi
	repo init \
		--manifest-url=git://git-master.nvidia.com/tegra/manifest.git 	\
		--manifest-branch=${BRANCH} 					\
		--manifest-name=automotive.xml 					\
		--groups=auto-foundation,auto-linux,auto-yocto,auto-qnx,virt-doc\
                ${REF_OPTION}

}

function repo-sync() {
	local JOPT=$*
	shift

	repo sync  ${JOPT}			\
		--no-tags 			\
		--current-branch		\
		--no-clone-bundle
}

function parent-has() {
	local PWD_SOURCE="$(pwd)"
	pushd "${PWD_SOURCE}" > /dev/null
	while [ "$(pwd)" != "/" ]; do
		for candidate in "$@"; do
			if [ ! -e $candidate ]; then
				cd ..
				continue 2 # continue the outer loop
			fi
		done
		break
	done
	if [ $# -ge 2 ]; then
		if [ "$2" != "" ]; then
			cd $2
		fi
	fi
	echo -ne $(pwd)
	popd >/dev/null
}

function is-under() {
	local PWD_SOURCE="$(pwd)"
	local R=0
	pushd "${PWD_SOURCE}" >/dev/null

	pushd $1 >/dev/null;
        if [ $? -ne 0 ]; then
		popd > /dev/null
		echo -ne 0
		return
	fi

        local P1=$(/bin/pwd); popd > /dev/null
	pushd $2 >/dev/null
	while true; do
		local P=$(/bin/pwd)
		if [ "$P" == "/" ]; then
			break
		fi
		if [ "$P" == "$P1" ]; then
			R=1
			break
		fi
		cd ..
	done
	popd >/dev/null
	popd >/dev/null
	echo -ne $R
}

function is-git-controlled() {
	local gitroot=$(parent-has ".git")
	if [ ${gitroot} == "/"  ]; then
		echo ''
		return
	fi
	echo "${gitroot}/.git"
}

function is-git-shallowed() {
	gitroot=$(is-git-controlled)
	if [ -z ${gitroot} ]; then
		echo -n "${COLOR_Black}"
		return
	fi
	echo -n "${COLOR_Green}"
}


function yocto-directory-check() {
  pushd ${VF} || return 1
  popd
  pushd ${VL} || return 1
  popd
  return 0
}

function yocto-topbuild() {
    local TBLL=/tmp/top-build-linux.log
    local TBFL=/tmp/top-build-foundation.log

    setup-vars-tegra
	_require_safe_directory "$VR" "VR" || return
	rm -rf -- "$VR/out/store_f" "$VR/out/store_l" "$VR/out/store"
    pushd $VL 2>&1 > /dev/null

    cd $VL/embedded/release
	rm -f -- "$TBLL"
    ./sdk/top-build $1 -p t186ref-lin64 -g external -x -s ${VR}/out/store_l 2>&1 | tee ${TBLL} || return
#    mv ${VR}/out/store ${VR}/out/store_l

    cd $VF/embedded/release
	rm -f -- "$TBFL"
    ./foundation/top-build -p t186ref $1 2>&1 | tee ${TBFL} || return
	rm -rf -- "$VR/out/store_f"
    mv $VR/out/store $VR/out/store_f

    popd 2>&1 > /dev/null

    notify "yocto-topbuild done"
}

function v5-install() {
  export _NV_INSTALL_LICENSE_BYPASS_="Destination Tegra Dominance"
  export D=$DISPLAY
  unset DISPLAY
  yes '' | bash $VL/out/store/drive-*-linux-*-oss-minimal-pdk.run
  yes '' | bash $VL/out/store/drive-*-linux-*-nv-minimal-sdk.run
  yes '' | bash $VL/out/store/drive-*-linux-*-nv-minimal-pdk.run
  yes '' | bash $VF/out/store/drive-*-foundation-*-release-sdk.run
  yes '' | bash $VF/out/store/drive-*-foundation-*-release-pdk.run
  export DISPLAY=$D
}

function yocto-setup() {
  setup-vars-tegra
  yocto-directory-check || return 1
	_require_safe_directory "$VR" "VR" || return
	rm -rf -- "$VR/out/install/pdk-all"
  mkdir -p $VR/out/install/pdk-all
  cd $VR/out/install/pdk-all
  tar -C $VR/out/install/pdk-all -zxf $VR/out/store_l/deferred_packaging/oss-src/oss-src.tgz
  tar -C $VL/out/install/pdk-all -jxf $VR/out/install/pdk-all/drive-t186ref-linux_src/kernel/linux.tar.bz2
  install-runs "${VR}/out/store_l" "${VR}/out/store_f"
  cd $VR/yocto
	if [ -e pdk ] && [ ! -L pdk ]; then
		echo "Refusing to replace non-symlink: $PWD/pdk" >&2
		return 1
	fi
	rm -f -- pdk
  ln -sf $VR/out/install/pdk-all pdk
#  D=${DISPLAY}
#  unset DISPLAY
#  export _NV_INSTALL_LICENSE_BYPASS_="Destination Tegra Dominance"
#  for run in \
#   $VR/out/store_l/drive*linux*oss-minimal-pdk.run   \
#   $VR/out/store_l/drive*linux*oss-minimal-sdk.run   \
#   $VR/out/store_l/drive*linux*nv-minimal-sdk.run    \
#   $VR/out/store_l/drive*linux*nv-minimal-pdk.run    \
#   $VR/out/store_f/drive*foundation*release-sdk.run  \
#   $VR/out/store_f/drive*foundation*release-pdk.run
#  do
#       echo "Installing ${run}"
#       yes '' | bash ${run}
#  done
#  export DISPLAY=${D}
#  cd $VR/yocto
#  rm pdk
#  ln -sf $VR/out/install/pdk-all pdk
}

function yocto-bb-shell() {
  yocto-build-env
  export SAVED_PS1="$PS1"
  export PS1="BB ${SAVED_PS1}"
  bash --noprofile
  export PS1="${SAVED_PS1}"
}

function yocto-build-env() {
  setup-vars-tegra
  yocto-directory-check || return 1
  cd $VR/yocto
  export TEMPLATECONF=$(pwd)/layers/meta-drive5/conf
  source oss/genivi-12/poky/oe-init-build-env
}

function yocto-build-target() {
  yocto-build-env
  bitbake "$@"
}

function yocto-build-ebp() {
  yocto-build-target tegra-early-boot-rootfs
}

function yocto-build() {
  yocto-build-target tegra-genivi-12-image
}

function yocto-build-all() {
  # Hi. You are building with meta-drive5 layer.
  #
  # The buildable images are:
  #  > quickboot
  #  > tegra-early-boot-rootfs
  #  > tegra-genivi-12-image
  #  > tegra-initramfs-boot
  for t in quickboot tegra-early-boot-rootfs tegra-genivi-12-image tegra-initramfs-boot; do
     yocto-build-target "" ${t} 2>&1 | tee ${t}.log
  done
  wkup
}

function git-changes() {
  local BRANCH=$1

  setup-vars-tegra
  repo forall -pc "git log --oneline HEAD...${BRANCH}"
}

function uuu() {
  python3 /home/dimka/P/nvidia/lab/u2n/u2n/u2n.py "$@"
}

function ls-usb-serials() {
  ls -l /sys/bus/usb-serial/devices/*/driver
}

function usb-path() {
  echo /sys$(udevadm info -q path /dev/bus/usb/$(printf "%03d" $1)/$(printf "%03d" $2))
}

function initramfs_unpack() {
  local IMG=$(realpath $1)
  local IPATH=$2
  local ZIP=$3

  force_sudo
  pushd $IPATH  2>&1 >/dev/null
  cat $IMG | sudo cpio --extract --make-directories --format=newc --no-absolute-filenames --owner=0:0
  popd 2>&1 >/dev/null
}

function initramfs_pack() {
  local IMG=$(realpath $1)
  local IPATH=$2
  local ZIP=$3

  force_sudo
  pushd $IPATH  2>&1 >/dev/null
  sudo find . -print0 | sudo cpio --null --create --format=newc >$IMG
  popd 2>&1 >/dev/null
}

function initramfs_do() {
  local R=$(mktemp -d)
  local I=$1

  force_sudo
  shift
  initramfs_unpack $I $R
  pushd $R
  eval "$*"
  popd
  initramfs_pack $I $R
	_require_safe_directory "$R" "temporary initramfs directory" || return
	sudo rm -rf -- "$R"
}

function initramfs_do_18() {
  initramfs_do "$VF/embedded/tools/boards/t186ref/yocto-tegra-initramfs-rootfs.img" "$@"
}

function initramfs_do_19() {
  initramfs_do "$VF/embedded/tools-t19x/boards/t194ref/yocto-tegra-initramfs-rootfs.img" "$@"
}

function pack_linux() {
  pushd $VL/out/embedded-linux-t186ref-release 2>&1 >/dev/null
  tar zcf linux.tgz nvidia/kernel/arch/arm64/boot/{z,}Image target_rootfs/lib/modules/
  popd 2>&1 >/dev/null
  ls -l $VL/out/embedded-linux-t186ref-release/linux.tgz
}

function notify() {
	printf '\e]9;%s\a' "$*"
}

function install-gcc-alternatives() {
	local v1=$1
	local v2=$2

	force_sudo
	sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${v1} 10
	sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${v2} 20

	sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${v1} 10
	sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${v2} 20

	sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
	sudo update-alternatives --set cc /usr/bin/gcc

	sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
	sudo update-alternatives --set c++ /usr/bin/g++
}

function list-gcc-versions() {
	update-alternatives --list gcc
}

function set-gcc-version() {
	local BIN="/usr/bin"
	[ -z "$1" ] && echo "Use set-cc-version VERSION" && return
	[ ! -f ${BIN}/gcc-$1 -o ! -f ${BIN}/g++-$1 ] && echo "gcc or g++ version $1 do not exist" && list-gcc-versions && return
	sudo update-alternatives --set gcc "${BIN}/gcc-$1"
	sudo update-alternatives --set g++ "${BIN}/g++-$1"
}

function q() {
	[ -z ${P4ROOT} ] && echo "P4ROOT should be set" && return
	export QNX_V="qnx710-ga1-6.5.4.2"
	export QNX_V_SHORT="qnx7"
	export QNX_HOST=${P4ROOT}/sw/tools/embedded/qnx/${QNX_V}/host/linux/x86_64
	export QNX_TARGET=${P4ROOT}/sw/tools/embedded/qnx/${QNX_V}/target/${QNX_V_SHORT}
	export PATH=${PATH}:${QNX_HOST}/usr/bin
	"$@"
}

function bind-linux() {
        nv f -- 'source ${VR}/foundation-t23x/mk_blob.sh; bind_partitions -b p3710-10-s05 linux'
}

function bind-pct() {
        local PCT=$1
        shift
        local NVARG=$1
        shift
        say "VR=${VR}\n"
        nv f ${NVARG} -- "source ${VR}/foundation-t23x/mk_blob.sh; bind_partitions -b p3710-10-s05 ${PCT} $*"
#        nv f ${ARG} -- 'source ${VR}/foundation-t23x/mk_blob.sh; bind_partitions -b p3710-10-a01-ct04 ${PCT} ${P}'
}


function bind-qnx-qnx() {
        bind-pct qnx-qnx "$@"
}

function bind-single-qnx() {
        bind-pct qnx "$@"
}

function create-images-colossus() {
	local NVARG=$1
        shift
	export NV_BOOTBURN_SAFETY_ALL_OPTIONS=1
	nv f "$NVARG" -- eenv "$VR/embedded/tools-t19x/scripts/bootburn/create_bsp_images.py" -b p3710-10-s05 -B qspi -r 1 -g /y/exports/p3710-10-s05 -D --chain A "$@"
#	nv f ${NVARG} -- eenv $VR/embedded/tools-t19x/scripts/bootburn/create_bsp_images.py -b  p3710-10-a01-ct04 -B qspi -r 1 -g /y/exports/p3710-10-s05 -D --chain A $*
#	nv f ${ARG} -- eenv $VR/embedded/tools-t19x/scripts/bootburn/create_bsp_images.py -b  p3710-10-a01-ct04 -B qspi -r 1 -g /y/exports/p3710-10-s05 -D --chain A $*
}

function set-colossus() {
	local colossus="$1"
        local colossus_user="dpervushin"

        if echo -n "$1" | grep --count --quiet "@"; then
             colossus=$(echo -n "$1" | cut -d '@' -f 2)
             colossus_user=$(echo -n "$1" | cut -d '@' -f 1)
        fi
	echo -n ${colossus} > ~/.nvidia-colossus-host
	echo -n ${colossus_user} > ~/.nvidia-colossus-user
}

function get-colossus-cred() {
        echo -n "$(get-colossus-user)@$(get-colossus-addr)"
}

function ssh-colossus() {
	ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" "$(get-colossus-cred)" "$@"
}

function get-colossus-addr() {
	cat ~/.nvidia-colossus-host
}

function get-colossus-user() {
	cat ~/.nvidia-colossus-user
}

function get-colossus() {
	say "Current COLOSSUS board credentials are $(get-colossus-cred)\n"
}

function rsync-colossus() {
	local colossus=${1:-$(get-colossus-addr)}
	local colossus_user=${2:-$(get-colossus-user)}
	if [ -z "${colossus}" ] ; then
		say "Remote host address should be set"
		return
	fi
	rsync -avz -e "ssh -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no -l ${colossus_user}" /y/exports/p3710-10-s05/ ${colossus}:y/p3710-10-s05/
}

function p3898-rflash() {
        AURIX=/dev/ttyUSB2
	ssh satyagi@10.41.21.223 bash << EOF
                set -x
		stty -F ${AURIX} raw 115200
		echo "tegrarecovery x1 on" > ${AURIX}
		sleep 1
		echo "tegrareset x1" > ${AURIX}
		sleep 5
                python3 /mnt/home3/dimka/p3898/tools/flashtools/bootburn/flash_bsp_images.py -b p3898-a01 -P /mnt/home3/dimka/p3898/6* $*
                sleep 5
		echo "tegrarecovery x1 off" > ${AURIX}
		sleep 1
		echo "tegrareset x1" > ${AURIX}
		sleep 5
EOF
}

function configure-serial-port() {
	local PORT=$1
	local PORTDEF=$2

	if [ -z ${PORT} ]; then
		PORT="${PORTDEF}"
	fi
	if [[ $PORT != /dev/* ]]; then
		if [[ $PORT != tty* ]]; then
			PORT="tty${PORT}"
		fi
		PORT="/dev/${PORT}"
	fi
	stty -F ${PORT} speed 115200 2>&1 >/dev/null
	echo -n ${PORT}
}

function gpush() {
	local BRANCH=$1
	git push origin HEAD:refs/for/${BRANCH}
}

function regenerate-ssh-keys() {
	LOCALHOST="127.1"
	KEYS="/tmp/ssh-keys.tar"

	ssh-keygen -f "/home/dimka/.ssh/known_hosts" -R ${LOCALHOST}
	for t in dsa ed25519 rsa; do
		yes 'y' | ssh-keygen -q -f ~/.ssh/id_${t} -t ${t} -N '' -C "dpervushin-${t}"
		echo -ne '\n'
		ssh-copy-id -i ~/.ssh/id_${t}.pub -oStrictHostKeyChecking=no ${LOCALHOST}
	done
	tar cf ${KEYS} ~/.ssh
#	for remote in $*; do
#		scp ${KEYS} ${remote}:/tmp
#	done
#	rm ${KEYS}
}

function call-traceprinter() {
	QNX_ROOT=${P4ROOT}/sw/tools/embedded/qnx/qnx710-ga1-6.5.4.1
	TRACEPRINTER=${QNX_ROOT}/host/linux/x86_64/usr/bin/traceprinter
	if [ ! -x ${TRACEPRINTER} ]; then
		say "QNX_ROOT\t\{QNX_ROOT}\nP4ROOT\t\t${P4ROOT}\nTRACEPRINTER\t${TRACEPRINTER}\n"
		say "Something does not exist...."
		return
	fi
	"${TRACEPRINTER}" "$@"
}

function forall() {
    find . -maxdepth 1 -type d  |  while read a; do if [ "$a" != "." ]; then "$1"; fi done
}

function all-gerrits() {
	local operation=$1
	cat | while read gerrit; do bash -c "${operation} ${gerrit}"; done
}

function list-functions() {
        declare -F | cut -f 3 -d ' ' | grep -v "_.*" | sort | column -c 3
}

function cross_compile() {
	nvl 'verbose; tmp kernel oldconfig' | command grep -o 'CROSS_COMPILE=[^ ]*' | head -1
}
shopt -s expand_aliases

VARIABLES="TARGET_O TARGET_U TARGET_O_PREFIX TARGET_CPUARCH TARGET_CROSS \
	TARGET_ROOT TARGET_TFTP TARGET_CODE TARGET_CODE2 TARGET_TARGET \
	TARGET_TARGET_BIN TARGET_PATH TARGET_UBOOT_BIN TARGET_MAKE TARGET_CP \
	TARGET_CUSTOM_CP JOPT \
	GIT_AUTHOR_EMAIL GIT_AUTHOR_NAME GIT_COMMITTER_EMAIL GIT_COMMITTER_NAME"
ROOT="/"
FQDN_PRJ_VARS=""
PRJ_VARS1="@project-vars"
PRJ_VARS2="project-vars"
DEFAULTS1="$HOME/defaults/$PRJ_VARS1"
DEFAULTS2="$HOME/defaults/$PRJ_VARS2"
SCRIPT=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)/$(basename "${BASH_SOURCE[0]}")
PRJ_SILENT=${PRJ_SILENT:=0}

_do_all "$VARIABLES" unset

[ -r "$DEFAULTS1" ] && . "$DEFAULTS1"
[ -r "$DEFAULTS2" ] && . "$DEFAULTS2"

pushd . > /dev/null

src[0]=""
src_index=-1

while [ "$(pwd)" != "$ROOT" ]; do
	[ -r "$PRJ_VARS1" ] && src[++src_index]="$(pwd)/$PRJ_VARS1"
	[ -r "$PRJ_VARS2" ] && src[++src_index]="$(pwd)/$PRJ_VARS2"
	cd ..
done
popd > /dev/null 2>&1

while [ $src_index -ge 0 ]; do
	a=${src[src_index--]}
	[ $PRJ_SILENT -eq 0 ] && say "### @@ $a\n"
	pushd "$(dirname "$a")" > /dev/null
	source ./"$(basename $a)"
	popd > /dev/null
done

TARGET_TARGET_BIN="${TARGET_TARGET_BIN:-$TARGET_TARGET-${TARGET_CODE}${TARGET_CODE2}}"
TARGET_PATH="${TARGET_PATH:-arch/$TARGET_CPUARCH/boot}"
TARGET_UBOOT_BIN="${TARGET_UBOOT_BIN:-uboot-$TARGET_CODE-dimka.bin}"
TARGET_O="${TARGET_O:-${TARGET_O_PREFIX}/o-$TARGET_CODE}"
TARGET_U="${TARGET_U:-${TARGET_O_PREFIX}/u-$TARGET_CODE}"
if [ -n "$TARGET_CP" ] && [ -z "$TARGET_CUSTOM_CP" ]; then
	TARGET_CUSTOM_CP="$TARGET_CP"
fi
TARGET_CUSTOM_CP="${TARGET_CUSTOM_CP:-cp}"

COLOR_Reset=""
COLOR_Black=""
COLOR_Red=""
COLOR_Green=""
COLOR_Yellow=""
COLOR_Blue=""
COLOR_Magenta=""
COLOR_Cyan=""
COLOR_White=""
if [ -n "${TERM:-}" ] && [ "$TERM" != "dumb" ]; then
	if command -v tput >/dev/null 2>&1 && tput colors >/dev/null 2>&1; then
		COLOR_Reset="$(tput sgr0)"
		COLOR_Black="$(tput setaf 0)"
		COLOR_Red="$(tput setaf 1)"
		COLOR_Green="$(tput setaf 2)"
		COLOR_Yellow="$(tput setaf 3)"
		COLOR_Blue="$(tput setaf 4)"
		COLOR_Magenta="$(tput setaf 5)"
		COLOR_Cyan="$(tput setaf 6)"
		COLOR_White="$(tput setaf 7)"
	else
		COLOR_Reset="$(printf '\033[0m')"
		COLOR_Black="$(printf '\033[30m')"
		COLOR_Red="$(printf '\033[31m')"
		COLOR_Green="$(printf '\033[32m')"
		COLOR_Yellow="$(printf '\033[33m')"
		COLOR_Blue="$(printf '\033[34m')"
		COLOR_Magenta="$(printf '\033[35m')"
		COLOR_Cyan="$(printf '\033[36m')"
		COLOR_White="$(printf '\033[37m')"
	fi
fi

# start with exporting variables...
_do_all "$VARIABLES" export
late_init
# the 2nd chance to export variables
_do_all "$VARIABLES" export

# aliases setup
alias ntg7gr='cd ~/projects/nvidia/v5/NTG7/R/tools/golden-regs-rel/1.7/gr_host_tools/tgv_tool'
alias asetup='export NV_BUILD_KERNEL_ACK_VERSION=6.1; export NV_BUILD_KERNEL_ACK=true; source build/envsetup.sh && choosecombo 1 generic_aaos 3'
alias diff='/usr/bin/diff -uNr -X ~/defaults/dontdiff'
alias hd='od -Ax -tx1z -v'
alias please='sudo'
alias ls='ls -CF '
alias wkup="echo $'\a'"
alias rootfs="yes | image delete_rootfs; image create_rootfs"
alias gca!="git commit --amend --no-edit"

function md() {
	mkdir "$1" && cd "$1"
}

# Local-only commands retained during consolidation.
function zap() {
	local ebk="%ebk"
	pushd "$VL/out/embedded-linux-t186ref-release/nvidia/kernel_early_boot/" || return
	mv kernel "$ebk"
	mv "$ebk"/* .
	_require_safe_directory "$PWD" "kernel early boot directory" || return
	rm -rf -- "$ebk"
	popd
}

function qnx-suspend() {
	local port
	port=$(configure-serial-port "$1" "ttyUSB2") || return
	echo 'echo 1 > /dev/nvsyseventclient/suspend' > "$port"
}

function mouse-driver() {
	force_sudo
	pushd ~/drivers/* || return
	set-gcc-version 9
	sudo make INTERFACE=all install && sudo /sbin/reboot
	popd
}

[ -r "$HOME/bin/nvgerrit-cli-aliases" ] && source "$HOME/bin/nvgerrit-cli-aliases"

if [[ $- == *i* ]]; then
	complete -cf sudo
fi

ME_SHORT=$(hostname -s)
ME=$(hostname -f 2>/dev/null || hostname)
case ${ME_SHORT} in
 dd|dpervushin-dt) COLOR='${COLOR_Yellow}' ;;
 mcdimka)       COLOR='${COLOR_Magenta}' ;;
 brainbox)      COLOR='${COLOR_Red}' ;;
 tower)		COLOR='${COLOR_Cyan}' ;;
 v)             COLOR='${COLOR_Blue}' ;;
 *)             COLOR='${COLOR_White}' ;;
esac

# do customization depending on host name
for CUSTOMIZATION_DIR in "${HOME}/hosts" "${HOME}/etc/hosts/" "${HOME}/etc" "/etc/hosts"; do
   CUSTOMIZATION_FOUND=""
   [ -z "${CUSTOMIZATION_FOUND}" ] && [ -f "${CUSTOMIZATION_DIR}/${ME}" ] && CUSTOMIZATION_FOUND=${CUSTOMIZATION_DIR}/${ME}
   [ -z "${CUSTOMIZATION_FOUND}" ] && [ -f "${CUSTOMIZATION_DIR}/${ME}.conf" ] && CUSTOMIZATION_FOUND=${CUSTOMIZATION_DIR}/${ME}.conf
   [ -z "${CUSTOMIZATION_FOUND}" ] && [ -f "${CUSTOMIZATION_DIR}/${ME_SHORT}" ] && CUSTOMIZATION_FOUND=${CUSTOMIZATION_DIR}/${ME_SHORT}
   [ -z "${CUSTOMIZATION_FOUND}" ] && [ -f "${CUSTOMIZATION_DIR}/${ME_SHORT}.conf" ] && CUSTOMIZATION_FOUND=${CUSTOMIZATION_DIR}/${ME_SHORT}.conf
   if [ -n "${CUSTOMIZATION_FOUND}" ]; then
	say "### Configuring using ${CUSTOMIZATION_FOUND}\n"
	source "${CUSTOMIZATION_FOUND}"
        break
   fi
done

export HISTTIMEFORMAT="%d/%m/%y %T "

export PROMPT_COMMAND="ps1_helper ${COLOR}"
if [[ $- == *i* ]] && [ "${SHELL_SCRIPTS_DAILY_CHECK:-1}" != "0" ]; then
	shell-scripts-check-daily
fi
if [ "x$1" == "x" ]; then
   cmd="setup"
   say "### calling setup\n"
else
   cmd=$1
fi

shift
say "### -> \"$cmd\" $*\n"
fix_arch
"$cmd" "$@"
